import {
  ModelDefinition,
  ModelPrice,
  ModelCapability,
  ProviderDefinition,
} from './types';

// Static provider + model registry — a fallback for providers without a live
// catalog API. Pricing here is an estimate and should be overridden by a live
// catalog fetch where the provider exposes one. Do not hardcode "current"
// prices as authoritative. `price` reflects the provider's officially stated
// model pricing when known; otherwise `isFree` is only true when the provider
// confirms free access.

export const PROVIDER_DEFINITIONS: ProviderDefinition[] = [
  {
    providerId: 'chutes',
    displayName: 'Chutes',
    authType: 'api_key',
    status: 'disconnected',
    connectedAt: null,
    envVar: 'CHUTES_API_KEY',
    serverConfigured: false,
    description: 'Composable inference for open-weight coding and reasoning models.',
    docsUrl: 'https://chutes.ai',
    exposesCatalogApi: true,
  },
  {
    providerId: 'openrouter',
    displayName: 'OpenRouter',
    authType: 'api_key',
    status: 'disconnected',
    connectedAt: null,
    envVar: 'OPENROUTER_API_KEY',
    serverConfigured: false,
    description: 'Unified API for hundreds of models with pricing and usage-based billing.',
    docsUrl: 'https://openrouter.ai',
    exposesCatalogApi: true,
  },
  {
    providerId: 'opencode',
    displayName: 'OpenCode Zen',
    authType: 'api_key',
    status: 'disconnected',
    connectedAt: null,
    envVar: 'OPENCODE_ZEN_API_KEY',
    serverConfigured: false,
    description: 'AI model gateway with free and paid tiers.',
    docsUrl: 'https://opencode.ai',
    exposesCatalogApi: true,
  },
  {
    providerId: 'openai',
    displayName: 'OpenAI',
    authType: 'api_key',
    status: 'disconnected',
    connectedAt: null,
    envVar: 'OPENAI_API_KEY',
    serverConfigured: false,
    description: 'Frontier models with strong tool calling and structured output.',
    docsUrl: 'https://platform.openai.com',
    exposesCatalogApi: false,
  },
  {
    providerId: 'gemini',
    displayName: 'Gemini',
    authType: 'api_key',
    status: 'disconnected',
    connectedAt: null,
    envVar: 'GEMINI_API_KEY',
    serverConfigured: false,
    description: 'Google models with massive context windows.',
    docsUrl: 'https://ai.google.dev',
    exposesCatalogApi: false,
  },
  {
    providerId: 'deepseek',
    displayName: 'DeepSeek',
    authType: 'api_key',
    status: 'disconnected',
    connectedAt: null,
    envVar: 'DEEPSEEK_API_KEY',
    serverConfigured: false,
    description: 'Cost-efficient coding and reasoning models.',
    docsUrl: 'https://platform.deepseek.com',
    exposesCatalogApi: false,
  },
  {
    providerId: 'zai',
    displayName: 'Z.AI',
    authType: 'api_key',
    status: 'disconnected',
    connectedAt: null,
    envVar: 'ZAI_API_KEY',
    serverConfigured: false,
    description: 'GLM family models for general coding and reasoning tasks.',
    docsUrl: 'https://www.z.ai',
    exposesCatalogApi: false,
  },
];

// A small helper to produce a price record without implying authoritative free
// status unless the provider confirms it.
function price(input: number | null, output: number | null, isFree: boolean): ModelPrice {
  return { input, output, isFree };
}

const cap = (...args: ModelCapability[]): ModelCapability[] => args;

// NOTE: Capability scores are aligned with the existing model-registry scores so
// the recommendation engine stays consistent with the live routing system.
export const STATIC_MODEL_REGISTRY: ModelDefinition[] = [
  // ── Chutes (recommended defaults) ──
  {
    providerId: 'chutes',
    modelId: 'deepseek-ai/DeepSeek-V4-Flash-0731-TEE',
    displayName: 'DeepSeek V4 Flash',
    contextWindow: 1_048_576,
    maxOutputTokens: 8192,
    price: price(0.11, 0.32, false),
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    capabilities: cap('coding', 'reasoning', 'fast', 'long_context', 'tool_calling', 'structured_output'),
    availability: 'unknown',
    scores: { coding: 5, reasoning: 5, speed: 4, longContext: 5 },
    tags: ['recommended', 'best-coding', 'fast', 'long-context', 'reasoning'],
    source: 'registry',
  },
  {
    providerId: 'chutes',
    modelId: 'Qwen/Qwen3-235B-A22B-Thinking-2507-TEE',
    displayName: 'Qwen3 235B A22B Thinking 2507',
    contextWindow: 262_144,
    maxOutputTokens: 8192,
    price: price(0.16, 0.48, false),
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    capabilities: cap('coding', 'reasoning', 'long_context', 'tool_calling', 'structured_output'),
    availability: 'unknown',
    scores: { coding: 5, reasoning: 5, speed: 3, longContext: 5 },
    tags: ['recommended', 'best-reasoning', 'complex-debugging', 'long-context', 'reasoning'],
    source: 'registry',
  },
  {
    providerId: 'chutes',
    modelId: 'Qwen/Qwen3.5-397B-A17B-TEE',
    displayName: 'Qwen3.5 397B A17B',
    contextWindow: 131_072,
    maxOutputTokens: 8192,
    price: price(0.2, 0.6, false),
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    capabilities: cap('coding', 'reasoning', 'tool_calling', 'structured_output'),
    availability: 'unknown',
    scores: { coding: 5, reasoning: 5, speed: 3, longContext: 5 },
    tags: ['best-coding', 'reasoning', 'complex-debugging'],
    source: 'registry',
  },
  {
    providerId: 'chutes',
    modelId: 'Qwen/Qwen3-32B-TEE',
    displayName: 'Qwen3 32B',
    contextWindow: 32_000,
    maxOutputTokens: 4096,
    price: price(0.08, 0.24, false),
    supportsReasoning: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    capabilities: cap('coding', 'fast', 'tool_calling', 'structured_output'),
    availability: 'unknown',
    scores: { coding: 4, reasoning: 4, speed: 4, longContext: 3 },
    tags: ['fast', 'value'],
    source: 'registry',
  },
  {
    providerId: 'chutes',
    modelId: 'moonshotai/Kimi-K2.6-TEE',
    displayName: 'Kimi K2.6',
    contextWindow: 131_072,
    maxOutputTokens: 8192,
    price: price(0.18, 0.54, false),
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    capabilities: cap('coding', 'reasoning', 'tool_calling', 'structured_output'),
    availability: 'unknown',
    scores: { coding: 5, reasoning: 5, speed: 3, longContext: 5 },
    tags: ['best-coding', 'reasoning'],
    source: 'registry',
  },

  // ── OpenCode Zen (free tier confirmed by provider gateways) ──
  ...zenModels(),

  // ── DeepSeek (paid) ──
  {
    providerId: 'deepseek',
    modelId: 'deepseek-v4-flash',
    displayName: 'DeepSeek V4 Flash',
    contextWindow: 131_072,
    maxOutputTokens: 8192,
    price: price(0.27, 1.1, false),
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    capabilities: cap('coding', 'reasoning', 'fast', 'tool_calling', 'structured_output'),
    availability: 'unknown',
    scores: { coding: 5, reasoning: 5, speed: 4, longContext: 5 },
    tags: ['best-coding', 'fast', 'reasoning'],
    source: 'registry',
  },
  {
    providerId: 'deepseek',
    modelId: 'deepseek-v4-pro',
    displayName: 'DeepSeek V4 Pro',
    contextWindow: 131_072,
    maxOutputTokens: 8192,
    price: price(0.54, 2.19, false),
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    capabilities: cap('coding', 'reasoning', 'tool_calling', 'structured_output'),
    availability: 'unknown',
    scores: { coding: 5, reasoning: 5, speed: 3, longContext: 5 },
    tags: ['best-coding', 'reasoning'],
    source: 'registry',
  },

  // ── Gemini (paid) ──
  {
    providerId: 'gemini',
    modelId: 'gemini-3.7-flash',
    displayName: 'Gemini 3.7 Flash',
    contextWindow: 1_048_576,
    maxOutputTokens: 32_768,
    price: price(0.6, 2.4, false),
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    capabilities: cap('coding', 'reasoning', 'fast', 'long_context', 'tool_calling', 'structured_output'),
    availability: 'unknown',
    scores: { coding: 4, reasoning: 4, speed: 4, longContext: 5 },
    tags: ['long-context', 'fast', 'reasoning'],
    source: 'registry',
  },
  {
    providerId: 'gemini',
    modelId: 'gemini-2.5-pro',
    displayName: 'Gemini 2.5 Pro',
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    price: price(1.25, 10.0, false),
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    capabilities: cap('coding', 'reasoning', 'long_context', 'tool_calling', 'structured_output'),
    availability: 'unknown',
    scores: { coding: 5, reasoning: 5, speed: 3, longContext: 5 },
    tags: ['best-reasoning', 'long-context'],
    source: 'registry',
  },

  // ── Z.AI / GLM ──
  {
    providerId: 'zai',
    modelId: 'glm-4.7-flash',
    displayName: 'GLM 4.7 Flash',
    contextWindow: 128_000,
    maxOutputTokens: 4096,
    price: price(null, null, false),
    supportsReasoning: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    capabilities: cap('coding', 'fast', 'tool_calling', 'structured_output'),
    availability: 'unknown',
    scores: { coding: 4, reasoning: 4, speed: 4, longContext: 4 },
    tags: ['fast', 'value'],
    source: 'registry',
  },
];

function zenModels(): ModelDefinition[] {
  return [
    {
      providerId: 'opencode',
      modelId: 'nemotron-3-ultra-free',
      displayName: 'Nemotron 3 Ultra (free)',
      contextWindow: 128_000,
      maxOutputTokens: 4096,
      price: price(0, 0, true),
      supportsReasoning: true,
      supportsToolCalling: true,
      supportsStructuredOutput: true,
      capabilities: cap('coding', 'reasoning', 'long_context', 'tool_calling', 'structured_output'),
      availability: 'unknown',
      scores: { coding: 4, reasoning: 5, speed: 3, longContext: 5 },
      tags: ['best-reasoning', 'free', 'long-context'],
      source: 'registry',
    },
    {
      providerId: 'opencode',
      modelId: 'nemotron-3.5-lightning-free',
      displayName: 'Nemotron 3.5 Lightning (free)',
      contextWindow: 128_000,
      maxOutputTokens: 4096,
      price: price(0, 0, true),
      supportsReasoning: false,
      supportsToolCalling: true,
      supportsStructuredOutput: true,
      capabilities: cap('coding', 'fast', 'tool_calling', 'structured_output'),
      availability: 'unknown',
      scores: { coding: 4, reasoning: 3, speed: 5, longContext: 3 },
      tags: ['fast', 'free'],
      source: 'registry',
    },
    {
      providerId: 'opencode',
      modelId: 'mimo-v2.5-free',
      displayName: 'Mimo v2.5 (free)',
      contextWindow: 128_000,
      maxOutputTokens: 4096,
      price: price(0, 0, true),
      supportsReasoning: true,
      supportsToolCalling: true,
      supportsStructuredOutput: true,
      capabilities: cap('coding', 'reasoning', 'tool_calling', 'structured_output'),
      availability: 'unknown',
      scores: { coding: 5, reasoning: 5, speed: 3, longContext: 4 },
      tags: ['best-coding', 'reasoning', 'free'],
      source: 'registry',
    },
    {
      providerId: 'opencode',
      modelId: 'big-pickle',
      displayName: 'Big Pickle',
      contextWindow: 128_000,
      maxOutputTokens: 4096,
      price: price(0, 0, true),
      supportsReasoning: true,
      supportsToolCalling: true,
      supportsStructuredOutput: true,
      capabilities: cap('coding', 'reasoning', 'tool_calling', 'structured_output'),
      availability: 'unknown',
      scores: { coding: 4, reasoning: 4, speed: 2, longContext: 4 },
      tags: ['reasoning', 'free'],
      source: 'registry',
    },
  ];
}

export function findStaticModel(providerId: string, modelId: string): ModelDefinition | undefined {
  return STATIC_MODEL_REGISTRY.find(
    (m) => m.providerId === providerId && m.modelId === modelId
  );
}